language: csharp
solution: BloomFilter/BloomFilter.sln
mono: none
dotnet: 2.1.301
install:
 - dotnet restore
 - nuget restore BloomFilter/BloomFilter.sln
 - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
 - xbuild /p:Configuration=Release BloomFilter/BloomFilter.sln
 - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./BloomFilter/BloomFilter.Tests/bin/Release/BloomFilter.Tests.dll
