language: csharp
mono: none
dotnet: 2.1.302
script:
  - dotnet restore
  - dotnet build ./BloomFilter/
  - dotnet build ./BloomFilter/BloomFilter/
  - dotnet test ./BloomFilter/BloomFilter.UnitTests/
  
