language: csharp
solution: BloomFilter/BloomFilter.sln
install:
  - nuget restore BloomFilter/BloomFilter.sln
  - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Debug BloomFilter/BloomFilter.sln
  - mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./BloomFilter/BloomFilter.UnitTests/bin/Debug/BloomFilter.UnitTests.dll
